### ISSUE TITLE
SSH Keys Without Passphrase's

### ISSUE THREAD

**Issue by jpe42** [NickCarneiro/remtail#3]
Is it possible to support private keys without passphrase's?  I get the following error with my current key.

```
/usr/local/lib/node_modules/remtail/node_modules/ssh2/lib/client.js:156
        throw new Error('Encrypted private key detected, but no passphrase giv
              ^
Error: Encrypted private key detected, but no passphrase given
    at Client.connect (/usr/local/lib/node_modules/remtail/node_modules/ssh2/lib/client.js:156:15)
    at main (/usr/local/lib/node_modules/remtail/index.js:120:41)
    at Object.<anonymous> (/usr/local/lib/node_modules/remtail/index.js:126:5)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
    at node.js:906:3
```

**Comment by NickCarneiro** [comment]
I have added support for ssh keys with passphrases in v0.0.4. It should autodetect them and prompt for the passphrase.
